### ISSUE TITLE
Chromium version incompatible with puppeteer version? 

### ISSUE THREAD

**Issue by NickStefan** [shawnliujw/puppeteer-lambda#30]
I'm running `"puppeteer-lambda": "1.1.3",` on Node 8.10 of lambda, and I'm getting this error from within chromium during a request:
```
{ Error: Protocol error (Fetch.enable): 'Fetch.enable' wasn't found
    at Promise (/var/task/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/var/task/node_modules/puppeteer/lib/Connection.js:182:12)
    at NetworkManager._updateProtocolRequestInterception (/var/task/node_modules/puppeteer/lib/NetworkManager.js:139:22)
    at NetworkManager.setRequestInterception (/var/task/node_modules/puppeteer/lib/NetworkManager.js:128:16)
    at Page.setRequestInterception (/var/task/node_modules/puppeteer/lib/Page.js:289:48)
    at Page.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:112:23)
    at makePage (/var/task/robots/capture.js:29:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Protocol error (Fetch.enable): \'Fetch.enable\' wasn\'t found' }
2019-10-03T01:23:43.126Z	edf24267-fab0-4261-b22a-db2c1a0a779e	results [ [ 'Error: Protocol error (Fetch.enable): \'Fetch.enable\' wasn\'t found\n    at Promise (/var/task/node_modules/puppeteer/lib/Connection.js:183:56)\n    at new Promise (<anonymous>)\n    at CDPSession.send (/var/task/node_modules/puppeteer/lib/Connection.js:182:12)\n    at NetworkManager._updateProtocolRequestInterception (/var/task/node_modules/puppeteer/lib/NetworkManager.js:139:22)\n    at NetworkManager.setRequestInterception (/var/task/node_modules/puppeteer/lib/NetworkManager.js:128:16)\n    at Page.setRequestInterception (/var/task/node_modules/puppeteer/lib/Page.js:289:48)\n    at Page.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:112:23)\n    at makePage (/var/task/robots/capture.js:29:16)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)'
```
It looks like there's a closed issue on puppeteer https://github.com/GoogleChrome/puppeteer/issues/4542  and their suggestion is make sure the chromium version matches the puppeteer version.

Is it possible that without pinning libraries, the current version of this library won't have matching chromium / puppeteer? 

If not that, then anything else you can think of would be appreciated. Thank you.

**Comment by NickStefan** [comment]
looks like it's installing chrome 69 along with puppeteer 1.20.0
```
2019-10-03T01:45:59.043Z	c98ca42f-f647-4cb6-9053-3464b7e5d399	{ Error: ENOENT: no such file or directory, access '/tmp/headless-chromium'
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/tmp/headless-chromium' }
2019-10-03T01:45:59.068Z	c98ca42f-f647-4cb6-9053-3464b7e5d399	setup local chrome
2019-10-03T01:46:03.167Z	c98ca42f-f647-4cb6-9053-3464b7e5d399	setup done
2019-10-03T01:46:03.502Z	c98ca42f-f647-4cb6-9053-3464b7e5d399	Launch chrome: HeadlessChrome/69.0.3497.81
```

**Comment by NickStefan** [comment]
I was able to "fix it" by changing/pinning puppeteer-lambda's puppeteer to version 1.8.0. I had to edit a package-lock.json and use `npm ci` in order to do that. I guess it would be nice to configure the dependency puppeteer. 

Or maybe Puppeteer core will fix the issue some day!

**Comment by shawnliujw** [comment]
@NickStefan  cool
